-- MySQL Script generated by MySQL Workbench
-- 02/04/17 16:27:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eagle173_boog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eagle173_boog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eagle173_boog` DEFAULT CHARACTER SET utf8 ;
USE `eagle173_boog` ;

-- -----------------------------------------------------
-- Table `eagle173_boog`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`arquivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `modulo` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`buffet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`buffet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_buffet_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `eagle173_boog`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`atracao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_atracao_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `eagle173_boog`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`cardapio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_cardapio_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `eagle173_boog`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`tipo_festa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`tipo_festa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_tipo_festa_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `eagle173_boog`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`decoracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`decoracao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`parceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`parceiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `id_imagem` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_parceiro_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_parceiro_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `eagle173_boog`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NULL,
  `nome_aniversariante` VARCHAR(255) NULL,
  `idade_aniversariante` VARCHAR(255) NULL,
  `id_tipo_festa` INT NULL,
  `data` DATE NULL,
  `id_decoracao` INT NULL,
  `tema` VARCHAR(255) NULL,
  `num_convidados` INT NULL,
  `onde_encontrou` VARCHAR(100) NULL,
  `obs` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_orcamento_tipo_festa_idx` (`id_tipo_festa` ASC),
  INDEX `idx_orcamento_decoracao_idx` (`id_decoracao` ASC),
  CONSTRAINT `idx_orcamento_tipo_festa`
    FOREIGN KEY (`id_tipo_festa`)
    REFERENCES `eagle173_boog`.`tipo_festa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx_orcamento_decoracao`
    FOREIGN KEY (`id_decoracao`)
    REFERENCES `eagle173_boog`.`decoracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `cep` VARCHAR(8) NULL,
  `endereco` VARCHAR(500) NULL,
  `cidade` VARCHAR(255) NULL,
  `telefone` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`aniversariante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`aniversariante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_aniversariante_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `idx_aniversariante_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `eagle173_boog`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eagle173_boog`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eagle173_boog`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
