-- MySQL Script generated by MySQL Workbench
-- 02/12/17 18:25:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boogabolbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boogabolbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boogabolbd` DEFAULT CHARACTER SET utf8 ;
USE `boogabolbd` ;

-- -----------------------------------------------------
-- Table `boogabolbd`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`arquivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `modulo` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`buffet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`buffet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_buffet_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `boogabolbd`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`atracao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_atracao_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `boogabolbd`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`cardapio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_cardapio_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `boogabolbd`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`tipo_festa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`tipo_festa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_tipo_festa_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `boogabolbd`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`decoracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`decoracao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`parceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`parceiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `id_imagem` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_parceiro_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_parceiro_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `boogabolbd`.`arquivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`orcamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NULL,
  `nome_aniversariante` VARCHAR(255) NULL,
  `idade_aniversariante` INT NULL,
  `id_tipo_festa` INT NULL,
  `data` DATE NULL,
  `id_decoracao` INT NULL,
  `tema` VARCHAR(255) NULL,
  `num_convidados` INT NULL,
  `onde_encontrou` VARCHAR(100) NULL,
  `obs` MEDIUMTEXT NOT NULL,
  `flag_lido` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_orcamento_tipo_festa_idx` (`id_tipo_festa` ASC),
  INDEX `idx_orcamento_decoracao_idx` (`id_decoracao` ASC),
  CONSTRAINT `idx_orcamento_tipo_festa`
    FOREIGN KEY (`id_tipo_festa`)
    REFERENCES `boogabolbd`.`tipo_festa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx_orcamento_decoracao`
    FOREIGN KEY (`id_decoracao`)
    REFERENCES `boogabolbd`.`decoracao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `cep` VARCHAR(8) NULL,
  `endereco` VARCHAR(500) NULL,
  `cidade` VARCHAR(255) NULL,
  `telefone` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`aniversariante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`aniversariante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_aniversariante_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `idx_aniversariante_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `boogabolbd`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boogabolbd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boogabolbd`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
