-- MySQL Script generated by MySQL Workbench
-- 01/20/17 00:07:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`arquivo` (
  `id_arquivo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `extensao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_arquivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`buffet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buffet` (
  `id_buffet` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id_buffet`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_buffet_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `mydb`.`arquivo` (`id_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atracao` (
  `id_atracao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id_atracao`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_atracao_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `mydb`.`arquivo` (`id_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cardapio` (
  `id_cardapio` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id_cardapio`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_cardapio_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `mydb`.`arquivo` (`id_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_festa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_festa` (
  `id_tipo_festa` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `id_imagem` INT NULL,
  PRIMARY KEY (`id_tipo_festa`),
  INDEX `idx_buffet_arquivo_idx` (`id_imagem` ASC),
  CONSTRAINT `idx_tipo_festa_arquivo`
    FOREIGN KEY (`id_imagem`)
    REFERENCES `mydb`.`arquivo` (`id_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`decoracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`decoracao` (
  `id_decoracao` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  PRIMARY KEY (`id_decoracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parceiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parceiro` (
  `id_parceiro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `id_logo` INT NOT NULL,
  PRIMARY KEY (`id_parceiro`),
  INDEX `idx_parceiro_arquivo_idx` (`id_logo` ASC),
  CONSTRAINT `idx_parceiro_arquivo`
    FOREIGN KEY (`id_logo`)
    REFERENCES `mydb`.`arquivo` (`id_arquivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orcamento` (
  `id_orcamento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NULL,
  `nome_aniversariante` VARCHAR(255) NULL,
  `idade_aniversariante` VARCHAR(255) NULL,
  `id_tipo_festa` INT NULL,
  `data` DATE NULL,
  `id_decoracao` INT NULL,
  `tema` VARCHAR(255) NULL,
  `num_convidados` INT NULL,
  `onde_encontrou` VARCHAR(100) NULL,
  `obs` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_orcamento`),
  INDEX `idx_orcamento_tipo_festa_idx` (`id_tipo_festa` ASC),
  INDEX `idx_orcamento_decoracao_idx` (`id_decoracao` ASC),
  CONSTRAINT `idx_orcamento_tipo_festa`
    FOREIGN KEY (`id_tipo_festa`)
    REFERENCES `mydb`.`tipo_festa` (`id_tipo_festa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idx_orcamento_decoracao`
    FOREIGN KEY (`id_decoracao`)
    REFERENCES `mydb`.`decoracao` (`id_decoracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `cep` VARCHAR(8) NULL,
  `endereco` VARCHAR(500) NULL,
  `cidade` VARCHAR(255) NULL,
  `telefone` VARCHAR(50) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aniversariante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aniversariante` (
  `id_aniversariante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id_aniversariante`),
  INDEX `idx_aniversariante_cliente_idx` (`id_cliente` ASC),
  CONSTRAINT `idx_aniversariante_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
